
* purpose
* hh dataset labeling 

* child health


lab var child_ill "Did your child have the following disease(s) in the past 2 weeks?"
lab var child_ill0 "No Diseases"
lab var child_ill1 "Diarrhoea"
lab var child_ill2 "Cough"
lab var child_ill3 "Fever"
lab var child_ill888 "Other Diseases"
lab var child_ill_oth "Others"
lab var child_diarrh_treat "Did you seek advice or treatment for the diarrhoea?"
lab var child_diarrh_notreat "Why didn't your child receive any treatment for diarrhea?Why didn't your child receive any treatment for diarrhea?"
lab var child_diarrh_notreat1 "No health department/facility"
lab var child_diarrh_notreat2 "Very far from health facility"
lab var child_diarrh_notreat3 "Not easy to go to health facility"
lab var child_diarrh_notreat4 "Expensive medical expense"
lab var child_diarrh_notreat5 "Don't think it's necessary to get treatment"
lab var child_diarrh_notreat6 "Get advice not to get treatment at health facility"
lab var child_diarrh_notreat7 "Received other treatment"
lab var child_diarrh_notreat8 "Don't know/Don't remember which treatment to receive"
lab var child_diarrh_notreat9 "Cost of transportation"
lab var child_diarrh_notreat10 "Fear of contracting Covid-19"
lab var child_diarrh_notreat11 "There's no family member to take care of children at home"
lab var child_diarrh_notreat12 "Insecurity due to active conflict"
lab var child_diarrh_notreat13 "Mobility restrictions (physical or mental)"
lab var child_diarrh_notreat14 "Health care provider was not there when I visited there"
lab var child_diarrh_notreat15 "Family doesn't allow"
lab var child_diarrh_notreat888 "Other"
lab var child_diarrh_notreat777 "No answer"
lab var child_diarrh_notreat999 "Don't know/Don't remember"
lab var child_diarrh_notreat_oth "Others"
lab var child_diarrh_notice "When did your child receive treatment after getting diarrhea?"
lab var child_diarrh_where "Where did you go for advice or treatment for diarrhoea?"
lab var child_diarrh_where_oth "Others"
lab var child_diarrh_who "Who provided advice or treatment for diarrhoea at that place?"
lab var child_diarrh_who_oth "Others"
lab var child_diarrh_pay "Did you pay for the advice or treatment?"
lab var child_diarrh_cope "If yes, did the cost requires you (your HH) to take any of the following coping mechanisms?"
lab var child_diarrh_cope1 "Used bank savings"
lab var child_diarrh_cope2 "Used cash savings"
lab var child_diarrh_cope3 "Reduced non-food consumption/expenditure"
lab var child_diarrh_cope4 "Reduced food consumption"
lab var child_diarrh_cope5 "Borrowed money"
lab var child_diarrh_cope6 "Sold off assets (e.g., jewellery, mobile, furniture) "
lab var child_diarrh_cope7 "Did nothing, although it was required"
lab var child_diarrh_cope8 "Did nothing, because it was not required"
lab var child_diarrh_cope9 "Reduced savings"
lab var child_diarrh_cope10 "Taking collateral loan"
lab var child_diarrh_cope11 "Requesting provision from parents (or) relatives"
lab var child_diarrh_cope12 "Taking the cash advance from the work"
lab var child_diarrh_cope13 "Relying on the donation of employers"
lab var child_diarrh_cope14 "Donations from charities, monasteries, or other institutions"
lab var child_diarrh_cope888 "Other (specify)"
lab var child_diarrh_cope666 "Refused"
lab var child_diarrh_cope_oth "Please specify other coping mechanism."
lab var child_cough_rapbth "Has (NAME) had fast, short, rapid breaths or difficulty breathing at any time in the last 2 weeks?"
lab var child_cough_diffbth "Was the fast or difficult breathing due to a problem in the chest or to a blocked or runny nose?"
lab var child_cough_treat "Has your child received any treatment for the cough or lung illness?"
lab var child_cough_notreat "Why didn't your child receive any treatment for cough or lung illness?"
lab var child_cough_notreat1 "No health department/facility"
lab var child_cough_notreat2 "Very far from health facility"
lab var child_cough_notreat3 "Not easy to go to health facility"
lab var child_cough_notreat4 "Expensive medical expense"
lab var child_cough_notreat5 "Don't think it's necessary to get treatment"
lab var child_cough_notreat6 "Get advice not to get treatment at health facility"
lab var child_cough_notreat7 "Received other treatment"
lab var child_cough_notreat8 "Don't know/Don't remember which treatment to receive"
lab var child_cough_notreat9 "Cost of transportation"
lab var child_cough_notreat10 "Fear of contracting Covid-19"
lab var child_cough_notreat11 "There's no family member to take care of children at home"
lab var child_cough_notreat12 "Insecurity due to active conflict"
lab var child_cough_notreat13 "Mobility restrictions (physical or mental)"
lab var child_cough_notreat14 "Health care provider was not there when I visited there"
lab var child_cough_notreat15 "Family doesn't allow"
lab var child_cough_notreat888 "Other"
lab var child_cough_notreat777 "No answer"
lab var child_cough_notreat999 "Don't know/Don't remember"
lab var child_cough_notreat_oth "Others"
lab var child_cough_notice "When did your child receive treatment after getting lung illness?"
lab var child_cough_where "Where did you go for advice or treatment for cough or lung illness?"
lab var child_cough_where_oth "Others"
lab var child_cough_who "Who provided advice or treatment for cough or lung illness at that place?"
lab var child_cough_who_oth "Others"
lab var child_cough_pay "Did you pay for the advice or treatment?"
lab var child_cough_cope "If yes, did the cost requires you (your HH) to take any of the following coping mechanisms?"
lab var child_cough_cope1 "Used bank savings"
lab var child_cough_cope2 "Used cash savings"
lab var child_cough_cope3 "Reduced non-food consumption/expenditure"
lab var child_cough_cope4 "Reduced food consumption"
lab var child_cough_cope5 "Borrowed money"
lab var child_cough_cope6 "Sold off assets (e.g., jewellery, mobile, furniture) "
lab var child_cough_cope7 "Did nothing, although it was required"
lab var child_cough_cope8 "Did nothing, because it was not required"
lab var child_cough_cope9 "Reduced savings"
lab var child_cough_cope10 "Taking collateral loan"
lab var child_cough_cope11 "Requesting provision from parents (or) relatives"
lab var child_cough_cope12 "Taking the cash advance from the work"
lab var child_cough_cope13 "Relying on the donation of employers"
lab var child_cough_cope14 "Donations from charities, monasteries, or other institutions"
lab var child_cough_cope888 "Other (specify)"
lab var child_cough_cope666 "Refused"
lab var child_cough_cope_oth "Please specify other coping mechanism."
lab var child_fever_treat "Has your child received any treatment for the fever?"
lab var child_fever_notreat "Why didn't your child receive any treatment for fever illness?"
lab var child_fever_notreat1 "No health department/facility"
lab var child_fever_notreat2 "Very far from health facility"
lab var child_fever_notreat3 "Not easy to go to health facility"
lab var child_fever_notreat4 "Expensive medical expense"
lab var child_fever_notreat5 "Don't think it's necessary to get treatment"
lab var child_fever_notreat6 "Get advice not to get treatment at health facility"
lab var child_fever_notreat7 "Received other treatment"
lab var child_fever_notreat8 "Don't know/Don't remember which treatment to receive"
lab var child_fever_notreat9 "Cost of transportation"
lab var child_fever_notreat10 "Fear of contracting Covid-19"
lab var child_fever_notreat11 "There's no family member to take care of children at home"
lab var child_fever_notreat12 "Insecurity due to active conflict"
lab var child_fever_notreat13 "Mobility restrictions (physical or mental)"
lab var child_fever_notreat14 "Health care provider was not there when I visited there"
lab var child_fever_notreat15 "Family doesn't allow"
lab var child_fever_notreat888 "Other"
lab var child_fever_notreat777 "No answer"
lab var child_fever_notreat999 "Don't know/Don't remember"
lab var child_fever_notreat_oth "Others"
lab var child_fever_notice "When did your child receive treatment after getting a high fever illness?"
lab var child_fever_where "Where did you go for advice or treatment for fever?"
lab var child_fever_where_oth "Others"
lab var child_fever_who "Who provided advice or treatment for fever at that place?"
lab var child_fever_who_oth "Others"
lab var child_fever_pay "Did you pay for the advice or treatment?"
lab var child_fever_cope "If yes, did the cost requires you (your HH) to take any of the following coping mechanisms?"
lab var child_fever_cope1 "Used bank savings"
lab var child_fever_cope2 "Used cash savings"
lab var child_fever_cope3 "Reduced non-food consumption/expenditure"
lab var child_fever_cope4 "Reduced food consumption"
lab var child_fever_cope5 "Borrowed money"
lab var child_fever_cope6 "Sold off assets (e.g., jewellery, mobile, furniture) "
lab var child_fever_cope7 "Did nothing, although it was required"
lab var child_fever_cope8 "Did nothing, because it was not required"
lab var child_fever_cope9 "Reduced savings"
lab var child_fever_cope10 "Taking collateral loan"
lab var child_fever_cope11 "Requesting provision from parents (or) relatives"
lab var child_fever_cope12 "Taking the cash advance from the work"
lab var child_fever_cope13 "Relying on the donation of employers"
lab var child_fever_cope14 "Donations from charities, monasteries, or other institutions"
lab var child_fever_cope888 "Other (specify)"
lab var child_fever_cope666 "Refused"
lab var child_fever_cope_oth "Please specify other coping mechanism."
lab var child_fever_malaria "When your child was having a high fever illness, did your child get testing for Malaria?"
lab var child_vaccin "Has your child received any vaccination since birth?"
lab var child_vaccin_card "Do you have a vaccination card?"
lab var child_birthwt "Do you know child weight at birth?"
lab var child_birthwt_unit "child's weight unit"
lab var child_birthwt_unit1 "kg"
lab var child_birthwt_unit2 "lb"
lab var child_birthwt_unit3 "oz"
lab var child_birthwt_kg "If yes, What was child's weight at birth? - KG"
lab var child_birthwt_lb "If yes, What was child's weight at birth?  - LB"
lab var child_birthwt_oz "If yes, What was child's weight at birth? - OZ"
lab var child_birthwt_doc "Child Birth Weight Source of informatio, Health card available?"
lab var child_vita "Did your child receive vitamin A in the past 6 months?"
lab var child_deworm "Did your child receive a deworming tablet in the past 6 months?"
