
* purpose
* hh dataset labeling 

* child iycf

lab var child_bf "Has the child ever consumed breastmilk in any of these ways?"
lab var child_eibf "How long after birth did you first put the child to the breast?"
lab var child_eibf_hrs "Hours"
lab var child_eibf_days "Days"
lab var chhild_addbf "In the first 3 days after delivery, was the child given anything to drink other than or in addition to breastmilk?"
lab var chhild_addbf1 "Plain water"
lab var chhild_addbf2 "Sugar water or glucose water"
lab var chhild_addbf3 "Powdered or fresh animal milk"
lab var chhild_addbf4 "Infant formula (Dumex, Nestle, etc)"
lab var chhild_addbf5 "No other liquid beside breastmilk"
lab var chhild_addbf888 "Other (specify)"
lab var chhild_addbf_oth "Others Specify"
lab var child_bfyest "Yesterday during the day or at night, did the child consume breastmilk from you or another woman, or did anyone give the child breastmilk using a spoon, cup or bottle?"
lab var child_water "Plain water"
lab var child_bms "Infant formula (example: Dumex, Similac, Aptimal, Humana, DG 3, DG 2, DG 1, etc.)"
lab var child_bms_freq "How many times yesterday during the day or night did the child consume the item?"
lab var child_milk "Milk such as tinned, powdered, or fresh animal milk (add locally available brand names of tinned and powdered milk)"
lab var child_milk_freq "How many times yesterday during the day or night did the child consume the item?"
lab var child_mproduct "Sour milk or yogurt"
lab var child_mproduct_freq "How many times yesterday during the day or night did the child consume the item?"
lab var child_juice "Juice or juice drinks"
lab var child_tea "Tea, coffee, or herbal drinks?"
lab var child_energyd "Sodas, malt drinks, sports drinks or energy drinks?"
lab var child_broth "Clear broth"
lab var child_porridge "Thin porridge"
lab var child_liquid "Other water-based liquids"
lab var child_liquid_oth "Please specify what is Other water-based liquids"
lab var info_solid_food "Please tell me everything that the child ate yesterday during the day or night (whether at home or outside the home)."
lab var child_rice "Bread, rice, noodles, or other foods made from grains, including thick grain-based porridge?"
lab var child_potatoes "White potatoes, white yams, manioc, cassava, or any other foods made from roots?"
lab var child_pumpkin "Pumpkin, carrots, squash, or sweet potatoes that are yellow or orange inside?"
lab var child_beans "Any foods made from beans, peas, lentils or nuts, including Plumpy nut?"
lab var child_leafyveg "Any dark green leafy vegetables?"
lab var child_mango "Ripe mangoes, ripe papayas or (insert other local vitamin A-rich fruits)?"
lab var child_fruit "Any other fruits or vegetables?"
lab var child_organ "Liver, kidney, heart or other organ meats?"
lab var child_beef "Any meat such as beef, pork, lamb, goat, chicken or duck?"
lab var child_fish "Fresh or dried fish, shellfish, or seafood?"
lab var child_insects "Grubs, snails or insects?"
lab var child_eggs "Eggs?"
lab var child_yogurt "Yogurt, other than yogurt drinks?"
lab var child_cheese "Cheese, or other milk products?"
lab var child_fat "Any oil, fats or butter, or foods made with any of these?"
lab var child_plam "Foods made with palm oil, penut oil, sunflower oil or any oil produced from vegetable?"
lab var child_sweets "Any sugary foods such as chocolates, sweets, candies, pastries, cakes or biscuits?"
lab var child_condiments "Condiments for flavor such as chilies, spices, herbs or fish powder?"
lab var child_yogurt_num "How many times did the child eat yogurt?"
lab var child_othfood "Other foods: please write down other foods in this box that the respondent mentioned but are not in the list above. When data are entered into the computer, the other foods will be assigned to one of the 7 categories of foods:"
lab var child_solid_flagnote "Please go back and check the food questions. It is less likely to happen that the child was not eating non of the main food items from C.23 - C.36 at yesterday. "
lab var child_food_freq "How many times did the child eat solid, semi-solid or soft foods other than liquids yesterday during the day or at night? "
lab var child_fortified "Now I would like to ask you about other foods the child may eat.  I am interested in whether your child had the item even if it was combined with other foods. Yesterday, during the day or night, did the child consume any [list iron fortified solid, semi-solid or soft foods designed specifically for infants and young children available in the local setting]?"
lab var child_sprinkles "Yesterday, during the day or night, did the child consume any food to which you added a powder or sprinkles like this? "
lab var child_supplement "Yesterday, during the day or night, did the child consume any [list lipid based nutrient supplement (LNS) available in the local setting. If Plumpy'nut is available locally, it should be included in the list]. Show pictures of common types of LNS available in the survey area."
lab var child_ironformula "Yesterday, during the day or night, did the child consume any [list iron fortified infant/toddler formulas available in the local setting]?"
lab var child_bottle "Did the child drink anything from a bottle with a nipple yesterday or last night?"
