
* purpose
* hh dataset labeling 

* child health

lab var info_mom_food "Yesterday during the day and night, what did you (${women_pos1}) eat at home or outside home?"
lab var mom_rice "Food from grains"
lab var mom_potatoes "White roots and tubers and plantains"
lab var mom_beans "Pulses (beans, peas and lentils)"
lab var mom_nuts "Nuts and seeds"
lab var mom_yogurt "Milk and milk products"
lab var mom_organ "Organ meat"
lab var mom_beef "Meat and poultry"
lab var mom_fish "Fish and seafood"
lab var mom_eggs "Eggs"
lab var mom_leafyveg "Dark green leafy vegetables"
lab var mom_pumpkin "Vitamin A-rich vegetables, roots and tubers"
lab var mom_mango "Vitamin A rich fruits"
lab var mom_veg "Other vegetables"
lab var mom_fruit "Other fruits"
lab var mom_fat "Oils and fats"
lab var mom_sweets "Sweets"
lab var mom_condiments "Condiments and seasoning"
lab var mom_food_flagnote "Please go back and check the food questions. It is less likely to happen that the Mother was not eating non of the main food items from E.1 - E.14 at yesterday. "
lab var mom_diet_norice "So, mother did not eat any rice yesterday? So, mother did not eat any rice yesterday? "
lab var mom_meal_freq "R. How many meals did you eat yesterday during the day and night?"
lab var anc_adopt "Does your youngest under 2 years old child is adopted child or not?"
lab var anc_yn "During your pregnancy for your youngest child less than 24 months old, did you attend antenatal care sessions?"
lab var anc_where "Where did you receive care your ANC?"
lab var anc_where_oth "Others Specify"
lab var anc_home_who "In the antenatal care sessions that you attended, whom did you see?"
lab var anc_home_who1 "Specialist "
lab var anc_home_who2 "Doctor "
lab var anc_home_who3 "Nurse "
lab var anc_home_who4 "Health assistant "
lab var anc_home_who5 "Private doctor "
lab var anc_home_who6 "LHV "
lab var anc_home_who7 "Midwife "
lab var anc_home_who8 "AMW "
lab var anc_home_who9 "Ethnic health worker"
lab var anc_home_who10 "Community Health Worker "
lab var anc_home_who11 "TBA"
lab var anc_home_who888 "Other (specify): "
lab var anc_home_who_oth "Others Specify"
lab var anc_home_visit "How many antenatal care sessions have you attended?"
lab var anc_hosp_who "In the antenatal care sessions that you attended, whom did you see?"
lab var anc_hosp_who1 "Specialist "
lab var anc_hosp_who2 "Doctor "
lab var anc_hosp_who3 "Nurse "
lab var anc_hosp_who4 "Health assistant "
lab var anc_hosp_who5 "Private doctor "
lab var anc_hosp_who6 "LHV "
lab var anc_hosp_who7 "Midwife "
lab var anc_hosp_who8 "AMW "
lab var anc_hosp_who9 "Ethnic health worker"
lab var anc_hosp_who10 "Community Health Worker "
lab var anc_hosp_who11 "TBA"
lab var anc_hosp_who888 "Other (specify): "
lab var anc_hosp_who_oth "Others Specify"
lab var anc_hosp_dist_dry "How long does it take you to get to this place where you receive antenatal care sessions during the dry season?"
lab var anc_hosp_dist_wet "How long does it take you to get to this place where you receive antenatal care sessions during the rainy season?"
lab var anc_hosp_visit "How many antenatal care sessions have you attended?"
lab var anc_pc_who "In the antenatal care sessions that you attended, whom did you see?"
lab var anc_pc_who1 "Specialist "
lab var anc_pc_who2 "Doctor "
lab var anc_pc_who3 "Nurse "
lab var anc_pc_who4 "Health assistant "
lab var anc_pc_who5 "Private doctor "
lab var anc_pc_who6 "LHV "
lab var anc_pc_who7 "Midwife "
lab var anc_pc_who8 "AMW "
lab var anc_pc_who9 "Ethnic health worker"
lab var anc_pc_who10 "Community Health Worker "
lab var anc_pc_who11 "TBA"
lab var anc_pc_who888 "Other (specify): "
lab var anc_pc_oth "Others Specify"
lab var anc_pc_dist_dry "How long does it take you to get to this place where you receive antenatal care sessions during the dry season?"
lab var anc_pc_dist_wet "How long does it take you to get to this place where you receive antenatal care sessions during the rainy season?"
lab var anc_pc_visit "How many antenatal care sessions have you attended?"
lab var anc_rhc_who "In the antenatal care sessions that you attended, whom did you see?"
lab var anc_rhc_who1 "Specialist "
lab var anc_rhc_who2 "Doctor "
lab var anc_rhc_who3 "Nurse "
lab var anc_rhc_who4 "Health assistant "
lab var anc_rhc_who5 "Private doctor "
lab var anc_rhc_who6 "LHV "
lab var anc_rhc_who7 "Midwife "
lab var anc_rhc_who8 "AMW "
lab var anc_rhc_who9 "Ethnic health worker"
lab var anc_rhc_who10 "Community Health Worker "
lab var anc_rhc_who11 "TBA"
lab var anc_rhc_who888 "Other (specify): "
lab var anc_rhc_who_oth "Others Specify"
lab var anc_rhc_dist_dry "How long does it take you to get to this place where you receive antenatal care sessions during the dry season?"
lab var anc_rhc_dist_wet "How long does it take you to get to this place where you receive antenatal care sessions during the rainy season?"
lab var anc_rhc_visit "How many antenatal care sessions have you attended?"
lab var anc_ehoc_who "In the antenatal care sessions that you attended, whom did you see?"
lab var anc_ehoc_who1 "Specialist "
lab var anc_ehoc_who2 "Doctor "
lab var anc_ehoc_who3 "Nurse "
lab var anc_ehoc_who4 "Health assistant "
lab var anc_ehoc_who5 "Private doctor "
lab var anc_ehoc_who6 "LHV "
lab var anc_ehoc_who7 "Midwife "
lab var anc_ehoc_who8 "AMW "
lab var anc_ehoc_who9 "Ethnic health worker"
lab var anc_ehoc_who10 "Community Health Worker "
lab var anc_ehoc_who11 "TBA"
lab var anc_ehoc_who888 "Other (specify): "
lab var anc_ehoc_who_oth "Others Specify"
lab var anc_ehoc_dist_dry "How long does it take you to get to this place where you receive antenatal care sessions during the dry season?"
lab var anc_ehoc_dist_wet "How long does it take you to get to this place where you receive antenatal care sessions during the rainy season?"
lab var anc_ehoc_visit "How many antenatal care sessions have you attended?"
lab var anc_ehom_who "In the antenatal care sessions that you attended, whom did you see?"
lab var anc_ehom_who1 "Specialist "
lab var anc_ehom_who2 "Doctor "
lab var anc_ehom_who3 "Nurse "
lab var anc_ehom_who4 "Health assistant "
lab var anc_ehom_who5 "Private doctor "
lab var anc_ehom_who6 "LHV "
lab var anc_ehom_who7 "Midwife "
lab var anc_ehom_who8 "AMW "
lab var anc_ehom_who9 "Ethnic health worker"
lab var anc_ehom_who10 "Community Health Worker "
lab var anc_ehom_who11 "TBA"
lab var anc_ehom_who888 "Other (specify): "
lab var anc_ehom_oth "Others Specify"
lab var anc_ehom_dist_dry "How long does it take you to get to this place where you receive antenatal care sessions during the dry season?"
lab var anc_ehom_dist_wet "How long does it take you to get to this place where you receive antenatal care sessions during the rainy season?"
lab var anc_ehom_visit "How many antenatal care sessions have you attended?"
lab var anc_vill_who "In the antenatal care sessions that you attended, whom did you see?"
lab var anc_vill_who1 "Specialist "
lab var anc_vill_who2 "Doctor "
lab var anc_vill_who3 "Nurse "
lab var anc_vill_who4 "Health assistant "
lab var anc_vill_who5 "Private doctor "
lab var anc_vill_who6 "LHV "
lab var anc_vill_who7 "Midwife "
lab var anc_vill_who8 "AMW "
lab var anc_vill_who9 "Ethnic health worker"
lab var anc_vill_who10 "Community Health Worker "
lab var anc_vill_who11 "TBA"
lab var anc_vill_who888 "Other (specify): "
lab var anc_vill_who_oth "Others Specify"
lab var anc_vill_dist_dry "How long does it take you to get to this place where you receive antenatal care sessions during the dry season?"
lab var anc_vill_dist_wet "How long does it take you to get to this place where you receive antenatal care sessions during the rainy season?"
lab var anc_vill_visit "How many antenatal care sessions have you attended?"
lab var anc_othp_who "In the antenatal care sessions that you attended, whom did you see?"
lab var anc_othp_who1 "Specialist "
lab var anc_othp_who2 "Doctor "
lab var anc_othp_who3 "Nurse "
lab var anc_othp_who4 "Health assistant "
lab var anc_othp_who5 "Private doctor "
lab var anc_othp_who6 "LHV "
lab var anc_othp_who7 "Midwife "
lab var anc_othp_who8 "AMW "
lab var anc_othp_who9 "Ethnic health worker"
lab var anc_othp_who10 "Community Health Worker "
lab var anc_othp_who11 "TBA"
lab var anc_othp_who888 "Other (specify): "
lab var anc_othp_who_oth "Others Specify"
lab var anc_othp_dist_dry "How long does it take you to get to this place where you receive antenatal care sessions during the dry season?"
lab var anc_othp_dist_wet "How long does it take you to get to this place where you receive antenatal care sessions during the rainy season?"
lab var anc_othp_visit "How many antenatal care sessions have you attended?"
lab var anc_bf_counselling "During your most recent pregnancy, did you ever receive any counselling about exclusive breastfeeding for the first 6 months?"
lab var anc_nut_counselling "During your most recent pregnancy, did you ever receive any counseling about proper maternal nutrition practices during pregnancy?"
lab var anc_cost "Were there any costs involved in attending the antenatal care sessions?"
lab var anc_cope "If yes, did the cost requires you (your HH) to take any of the following coping mechanisms?"
lab var anc_cope1 "Used bank savings"
lab var anc_cope2 "Used cash savings"
lab var anc_cope3 "Reduced non-food consumption/expenditure"
lab var anc_cope4 "Reduced food consumption"
lab var anc_cope5 "Borrowed money"
lab var anc_cope6 "Sold off assets (e.g., jewellery, mobile, furniture) "
lab var anc_cope7 "Did nothing, although it was required"
lab var anc_cope8 "Did nothing, because it was not required"
lab var anc_cope9 "Reduced savings"
lab var anc_cope10 "Taking collateral loan"
lab var anc_cope11 "Requesting provision from parents (or) relatives"
lab var anc_cope12 "Taking the cash advance from the work"
lab var anc_cope13 "Relying on the donation of employers"
lab var anc_cope14 "Donations from charities, monasteries, or other institutions"
lab var anc_cope888 "Other (specify)"
lab var anc_cope666 "Refused"
lab var anc_cope_oth "Please specify other coping mechanism."
lab var anc_noreason "Why are you not attending any antenatal care sessions for your pregnancy for your youngest child less than 24 years old?"
lab var anc_noreason1 "Not important"
lab var anc_noreason2 "Very far"
lab var anc_noreason3 "Family doesn't allow "
lab var anc_noreason4 "There is no family member to accompany me. "
lab var anc_noreason5 "There is no health service nearby."
lab var anc_noreason6 "There is no health care provider nearby."
lab var anc_noreason7 "Financial difficulty"
lab var anc_noreason8 "Cost of transportation"
lab var anc_noreason9 "Fear of contracting Covid-19"
lab var anc_noreason10 "There's no family member to take care of children at home"
lab var anc_noreason11 "Insecurity due to active conflict"
lab var anc_noreason12 "Mobility restrictions (physical or mental)"
lab var anc_noreason13 "Health care provider was not there when I visited there "
lab var anc_noreason888 "Other (Please specify) "
lab var anc_noreason999 "Don't know/Don't remember"
lab var anc_noreason777 "Refused"
lab var anc_noreason_oth "I. Other (specify):"
lab var anc_restrict "Did you avoid eating any particular kind of food for your pregnancy for your youngest child less than 24 years old?"
lab var anc_restrict_item "What type of food did you avoid during your pregnancy?"
lab var anc_restrict_item1 "Vegetables"
lab var anc_restrict_item2 "Fruits"
lab var anc_restrict_item3 "Grains"
lab var anc_restrict_item4 "Meat"
lab var anc_restrict_item5 "Fish"
lab var anc_restrict_item6 "Diary foods"
lab var anc_restrict_item888 "Other (specify)"
lab var anc_restrict_item_oth "Please specify the type of food."
lab var anc_restrict_why "Why did you avoid eating those kinds of food for your pregnancy for your youngest child less than 24 years old?"
lab var anc_restrict_why_oth "I. Other (specify):"
lab var anc_bone "Did you take B1 tablets during your previous pregnancy?"
lab var anc_rion "Did you take iron+folic/ mincronutrient/ prenatal tablets during your previous pregnancy?"
lab var anc_iron_freq "Iron+folic/mincronutrient/prenatal consumption pattern."
lab var anc_iron_freq_lab "0"
lab var anc_iron_count "Please specify the number of tablet per ${anc_iron_freq_lab}"
lab var anc_rion_length "For how long did you take the iron+folic/mincronutrient/prenatal tablets?"
lab var anc_rion_length_oth "Please specify the number of months."
lab var anc_iron_cost "Where there any costs involved in taking iron+folic/mincronutrient/prenatal tablets?"
lab var anc_iron_source "From which source did you get iron+folic/mincronutrient/prenatal tablets?"
lab var anc_iron_source1 "Government hospital"
lab var anc_iron_source2 "Private Clinic"
lab var anc_iron_source3 "SRHC-RHC"
lab var anc_iron_source4 "Routine ANC place within village/ward"
lab var anc_iron_source5 "EHO Clinic"
lab var anc_iron_source888 "Other (specify)"
lab var anc_iron_source_oth "Please specify the source. "
lab var deliv_place "For your pregnancy for your youngest child less than 24 years old, were did you deliver your baby?"
lab var deliv_place_oth "Others Specify"
lab var deliv_assist "Who assisted with the delivery?"
lab var deliv_assist_oth "Others Specify"
lab var child_hepatitisb "Did your child receive Hepatitis B birth dose vaccine within 24 hours after delivery?"
lab var deliv_cost "Were there any costs involved in the delivery, e.g. user fees, medicines, transport?"
lab var deliv_cope "If yes, did the cost requires you (your HH) to take any of the following coping mechanisms?"
lab var deliv_cope1 "Used bank savings"
lab var deliv_cope2 "Used cash savings"
lab var deliv_cope3 "Reduced non-food consumption/expenditure"
lab var deliv_cope4 "Reduced food consumption"
lab var deliv_cope5 "Borrowed money"
lab var deliv_cope6 "Sold off assets (e.g., jewellery, mobile, furniture) "
lab var deliv_cope7 "Did nothing, although it was required"
lab var deliv_cope8 "Did nothing, because it was not required"
lab var deliv_cope9 "Reduced savings"
lab var deliv_cope10 "Taking collateral loan"
lab var deliv_cope11 "Requesting provision from parents (or) relatives"
lab var deliv_cope12 "Taking the cash advance from the work"
lab var deliv_cope13 "Relying on the donation of employers"
lab var deliv_cope14 "Donations from charities, monasteries, or other institutions"
lab var deliv_cope888 "Other (specify)"
lab var deliv_cope666 "Refused"
lab var deliv_cope_oth "Please specify other coping mechanism."
lab var pnc_yn "After delivering your youngest child less than 24 years old, did you have your health checked?"
lab var pnc_checktime "How long after delivery did you receive a health check?"
lab var pnc_checkunit "Select Unit"
lab var pnc_where "Where did you receive care your PNC?"
lab var pnc_where_oth "Others Specify"
lab var pnc_home_who "Who checked on your health?"
lab var pnc_home_who1 "Specialist "
lab var pnc_home_who2 "Doctor "
lab var pnc_home_who3 "Nurse "
lab var pnc_home_who4 "Health assistant "
lab var pnc_home_who5 "Private doctor "
lab var pnc_home_who6 "LHV "
lab var pnc_home_who7 "Midwife "
lab var pnc_home_who8 "AMW "
lab var pnc_home_who9 "Ethnic health worker"
lab var pnc_home_who10 "Community Health Worker "
lab var pnc_home_who11 "TBA"
lab var pnc_home_who888 "Other (specify): "
lab var pnc_home_oth "Others Specify"
lab var pnc_home_visit "How many times has your health been checked within 6 weeks after delivery?"
lab var pnc_hosp_who "Who checked on your health?"
lab var pnc_hosp_who1 "Specialist "
lab var pnc_hosp_who2 "Doctor "
lab var pnc_hosp_who3 "Nurse "
lab var pnc_hosp_who4 "Health assistant "
lab var pnc_hosp_who5 "Private doctor "
lab var pnc_hosp_who6 "LHV "
lab var pnc_hosp_who7 "Midwife "
lab var pnc_hosp_who8 "AMW "
lab var pnc_hosp_who9 "Ethnic health worker"
lab var pnc_hosp_who10 "Community Health Worker "
lab var pnc_hosp_who11 "TBA"
lab var pnc_hosp_who888 "Other (specify): "
lab var pnc_hosp_who_oth "Others Specify"
lab var pnc_hosp_visit "How many times has your health been checked within 6 weeks after delivery?"
lab var pnc_pc_who "Who checked on your health?"
lab var pnc_pc_who1 "Specialist "
lab var pnc_pc_who2 "Doctor "
lab var pnc_pc_who3 "Nurse "
lab var pnc_pc_who4 "Health assistant "
lab var pnc_pc_who5 "Private doctor "
lab var pnc_pc_who6 "LHV "
lab var pnc_pc_who7 "Midwife "
lab var pnc_pc_who8 "AMW "
lab var pnc_pc_who9 "Ethnic health worker"
lab var pnc_pc_who10 "Community Health Worker "
lab var pnc_pc_who11 "TBA"
lab var pnc_pc_who888 "Other (specify): "
lab var pnc_pc_oth "Others Specify"
lab var pnc_pc_visit "How many times has your health been checked within 6 weeks after delivery?"
lab var pnc_rhc_who "Who checked on your health?"
lab var pnc_rhc_who1 "Specialist "
lab var pnc_rhc_who2 "Doctor "
lab var pnc_rhc_who3 "Nurse "
lab var pnc_rhc_who4 "Health assistant "
lab var pnc_rhc_who5 "Private doctor "
lab var pnc_rhc_who6 "LHV "
lab var pnc_rhc_who7 "Midwife "
lab var pnc_rhc_who8 "AMW "
lab var pnc_rhc_who9 "Ethnic health worker"
lab var pnc_rhc_who10 "Community Health Worker "
lab var pnc_rhc_who11 "TBA"
lab var pnc_rhc_who888 "Other (specify): "
lab var pnc_rhc_who_oth "Others Specify"
lab var pnc_rhc_visit "How many times has your health been checked within 6 weeks after delivery?"
lab var pnc_ehoc_who "Who checked on your health?"
lab var pnc_ehoc_who1 "Specialist "
lab var pnc_ehoc_who2 "Doctor "
lab var pnc_ehoc_who3 "Nurse "
lab var pnc_ehoc_who4 "Health assistant "
lab var pnc_ehoc_who5 "Private doctor "
lab var pnc_ehoc_who6 "LHV "
lab var pnc_ehoc_who7 "Midwife "
lab var pnc_ehoc_who8 "AMW "
lab var pnc_ehoc_who9 "Ethnic health worker"
lab var pnc_ehoc_who10 "Community Health Worker "
lab var pnc_ehoc_who11 "TBA"
lab var pnc_ehoc_who888 "Other (specify): "
lab var pnc_ehoc_who_oth "Others Specify"
lab var pnc_ehoc_visit "How many times has your health been checked within 6 weeks after delivery?"
lab var pnc_ehom_who "Who checked on your health?"
lab var pnc_ehom_who1 "Specialist "
lab var pnc_ehom_who2 "Doctor "
lab var pnc_ehom_who3 "Nurse "
lab var pnc_ehom_who4 "Health assistant "
lab var pnc_ehom_who5 "Private doctor "
lab var pnc_ehom_who6 "LHV "
lab var pnc_ehom_who7 "Midwife "
lab var pnc_ehom_who8 "AMW "
lab var pnc_ehom_who9 "Ethnic health worker"
lab var pnc_ehom_who10 "Community Health Worker "
lab var pnc_ehom_who11 "TBA"
lab var pnc_ehom_who888 "Other (specify): "
lab var pnc_ehom_oth "Others Specify"
lab var pnc_ehom_visit "How many times has your health been checked within 6 weeks after delivery?"
lab var pnc_vill_who "Who checked on your health?"
lab var pnc_vill_who1 "Specialist "
lab var pnc_vill_who2 "Doctor "
lab var pnc_vill_who3 "Nurse "
lab var pnc_vill_who4 "Health assistant "
lab var pnc_vill_who5 "Private doctor "
lab var pnc_vill_who6 "LHV "
lab var pnc_vill_who7 "Midwife "
lab var pnc_vill_who8 "AMW "
lab var pnc_vill_who9 "Ethnic health worker"
lab var pnc_vill_who10 "Community Health Worker "
lab var pnc_vill_who11 "TBA"
lab var pnc_vill_who888 "Other (specify): "
lab var pnc_vill_who_oth "Others Specify"
lab var pnc_vill_visit "How many times has your health been checked within 6 weeks after delivery?"
lab var pnc_othp_who "Who checked on your health?"
lab var pnc_othp_who1 "Specialist "
lab var pnc_othp_who2 "Doctor "
lab var pnc_othp_who3 "Nurse "
lab var pnc_othp_who4 "Health assistant "
lab var pnc_othp_who5 "Private doctor "
lab var pnc_othp_who6 "LHV "
lab var pnc_othp_who7 "Midwife "
lab var pnc_othp_who8 "AMW "
lab var pnc_othp_who9 "Ethnic health worker"
lab var pnc_othp_who10 "Community Health Worker "
lab var pnc_othp_who11 "TBA"
lab var pnc_othp_who888 "Other (specify): "
lab var pnc_othp_who_oth "Others Specify"
lab var pnc_othp_visit "How many times has your health been checked within 6 weeks after delivery?"
lab var pnc_bone "Did you take B1 tablets after delivery?"
lab var pnc_bone_months "Months"
lab var pnc_bone_weeks "Weeks"
lab var pnc_cost "Were there any costs involved in your Postnatal Care (PNC)  care?"
lab var pnc_cope "If yes, did the cost requires you (your HH) to take any of the following coping mechanisms?"
lab var pnc_cope1 "Used bank savings"
lab var pnc_cope2 "Used cash savings"
lab var pnc_cope3 "Reduced non-food consumption/expenditure"
lab var pnc_cope4 "Reduced food consumption"
lab var pnc_cope5 "Borrowed money"
lab var pnc_cope6 "Sold off assets (e.g., jewellery, mobile, furniture) "
lab var pnc_cope7 "Did nothing, although it was required"
lab var pnc_cope8 "Did nothing, because it was not required"
lab var pnc_cope9 "Reduced savings"
lab var pnc_cope10 "Taking collateral loan"
lab var pnc_cope11 "Requesting provision from parents (or) relatives"
lab var pnc_cope12 "Taking the cash advance from the work"
lab var pnc_cope13 "Relying on the donation of employers"
lab var pnc_cope14 "Donations from charities, monasteries, or other institutions"
lab var pnc_cope888 "Other (specify)"
lab var pnc_cope666 "Refused"
lab var pnc_cope_oth "Please specify other coping mechanism."
lab var nbc_yn "Was your youngest child checked within 24 hours after birth?"
lab var nbc_2days_yn "Was your youngest child checked within 2 days after birth?"
lab var nbc_where "Where did you go and check your child health within 2 days after delivery?"
lab var nbc_where_oth "Others Specify"
lab var nbc_home_who "Who checked your child health within 2 days after delivery?"
lab var nbc_home_who1 "Specialist "
lab var nbc_home_who2 "Doctor "
lab var nbc_home_who3 "Nurse "
lab var nbc_home_who4 "Health assistant "
lab var nbc_home_who5 "Private doctor "
lab var nbc_home_who6 "LHV "
lab var nbc_home_who7 "Midwife "
lab var nbc_home_who8 "AMW "
lab var nbc_home_who9 "Ethnic health worker"
lab var nbc_home_who10 "Community Health Worker "
lab var nbc_home_who11 "TBA"
lab var nbc_home_who888 "Other (specify): "
lab var nbc_home_oth "Others Specify"
lab var nbc_home_visit "How many times has you check your child health within 2 days after delivery?"
lab var nbc_hosp_who "Who checked your child health within 2 days after delivery?"
lab var nbc_hosp_who1 "Specialist "
lab var nbc_hosp_who2 "Doctor "
lab var nbc_hosp_who3 "Nurse "
lab var nbc_hosp_who4 "Health assistant "
lab var nbc_hosp_who5 "Private doctor "
lab var nbc_hosp_who6 "LHV "
lab var nbc_hosp_who7 "Midwife "
lab var nbc_hosp_who8 "AMW "
lab var nbc_hosp_who9 "Ethnic health worker"
lab var nbc_hosp_who10 "Community Health Worker "
lab var nbc_hosp_who11 "TBA"
lab var nbc_hosp_who888 "Other (specify): "
lab var nbc_hosp_who_oth "Others Specify"
lab var nbc_hosp_visit "How many times has you check your child health within 2 days after delivery?"
lab var nbc_pc_who "Who checked your child health within 2 days after delivery?"
lab var nbc_pc_who1 "Specialist "
lab var nbc_pc_who2 "Doctor "
lab var nbc_pc_who3 "Nurse "
lab var nbc_pc_who4 "Health assistant "
lab var nbc_pc_who5 "Private doctor "
lab var nbc_pc_who6 "LHV "
lab var nbc_pc_who7 "Midwife "
lab var nbc_pc_who8 "AMW "
lab var nbc_pc_who9 "Ethnic health worker"
lab var nbc_pc_who10 "Community Health Worker "
lab var nbc_pc_who11 "TBA"
lab var nbc_pc_who888 "Other (specify): "
lab var nbc_pc_oth "Others Specify"
lab var nbc_pc_visit "How many times has you check your child health within 2 days after delivery?"
lab var nbc_rhc_who "Who checked your child health within 2 days after delivery?"
lab var nbc_rhc_who1 "Specialist "
lab var nbc_rhc_who2 "Doctor "
lab var nbc_rhc_who3 "Nurse "
lab var nbc_rhc_who4 "Health assistant "
lab var nbc_rhc_who5 "Private doctor "
lab var nbc_rhc_who6 "LHV "
lab var nbc_rhc_who7 "Midwife "
lab var nbc_rhc_who8 "AMW "
lab var nbc_rhc_who9 "Ethnic health worker"
lab var nbc_rhc_who10 "Community Health Worker "
lab var nbc_rhc_who11 "TBA"
lab var nbc_rhc_who888 "Other (specify): "
lab var nbc_rhc_who_oth "Others Specify"
lab var nbc_rhc_visit "How many times has you check your child health within 2 days after delivery?"
lab var nbc_ehoc_who "Who checked your child health within 2 days after delivery?"
lab var nbc_ehoc_who1 "Specialist "
lab var nbc_ehoc_who2 "Doctor "
lab var nbc_ehoc_who3 "Nurse "
lab var nbc_ehoc_who4 "Health assistant "
lab var nbc_ehoc_who5 "Private doctor "
lab var nbc_ehoc_who6 "LHV "
lab var nbc_ehoc_who7 "Midwife "
lab var nbc_ehoc_who8 "AMW "
lab var nbc_ehoc_who9 "Ethnic health worker"
lab var nbc_ehoc_who10 "Community Health Worker "
lab var nbc_ehoc_who11 "TBA"
lab var nbc_ehoc_who888 "Other (specify): "
lab var nbc_ehoc_who_oth "Others Specify"
lab var nbc_ehoc_visit "How many times has you check your child health within 2 days after delivery?"
lab var nbc_ehom_who "Who checked your child health within 2 days after delivery?"
lab var nbc_ehom_who1 "Specialist "
lab var nbc_ehom_who2 "Doctor "
lab var nbc_ehom_who3 "Nurse "
lab var nbc_ehom_who4 "Health assistant "
lab var nbc_ehom_who5 "Private doctor "
lab var nbc_ehom_who6 "LHV "
lab var nbc_ehom_who7 "Midwife "
lab var nbc_ehom_who8 "AMW "
lab var nbc_ehom_who9 "Ethnic health worker"
lab var nbc_ehom_who10 "Community Health Worker "
lab var nbc_ehom_who11 "TBA"
lab var nbc_ehom_who888 "Other (specify): "
lab var nbc_ehom_oth "Others Specify"
lab var nbc_ehom_visit "How many times has you check your child health within 2 days after delivery?"
lab var nbc_vill_who "Who checked your child health within 2 days after delivery?"
lab var nbc_vill_who1 "Specialist "
lab var nbc_vill_who2 "Doctor "
lab var nbc_vill_who3 "Nurse "
lab var nbc_vill_who4 "Health assistant "
lab var nbc_vill_who5 "Private doctor "
lab var nbc_vill_who6 "LHV "
lab var nbc_vill_who7 "Midwife "
lab var nbc_vill_who8 "AMW "
lab var nbc_vill_who9 "Ethnic health worker"
lab var nbc_vill_who10 "Community Health Worker "
lab var nbc_vill_who11 "TBA"
lab var nbc_vill_who888 "Other (specify): "
lab var nbc_vill_who_oth "Others Specify"
lab var nbc_vill_visit "How many times has you check your child health within 2 days after delivery?"
lab var nbc_othp_who "Who checked your child health within 2 days after delivery?"
lab var nbc_othp_who1 "Specialist "
lab var nbc_othp_who2 "Doctor "
lab var nbc_othp_who3 "Nurse "
lab var nbc_othp_who4 "Health assistant "
lab var nbc_othp_who5 "Private doctor "
lab var nbc_othp_who6 "LHV "
lab var nbc_othp_who7 "Midwife "
lab var nbc_othp_who8 "AMW "
lab var nbc_othp_who9 "Ethnic health worker"
lab var nbc_othp_who10 "Community Health Worker "
lab var nbc_othp_who11 "TBA"
lab var nbc_othp_who888 "Other (specify): "
lab var nbc_othp_who_oth "Others Specify"
lab var nbc_othp_visit "How many times has you check your child health within 2 days after delivery?"
lab var nbc_cost "Were there any costs involved in your youngest child's newborn care?"
lab var nbc_cope "If yes, did the cost requires you (your HH) to take any of the following coping mechanisms?"
lab var nbc_cope1 "Used bank savings"
lab var nbc_cope2 "Used cash savings"
lab var nbc_cope3 "Reduced non-food consumption/expenditure"
lab var nbc_cope4 "Reduced food consumption"
lab var nbc_cope5 "Borrowed money"
lab var nbc_cope6 "Sold off assets (e.g., jewellery, mobile, furniture) "
lab var nbc_cope7 "Did nothing, although it was required"
lab var nbc_cope8 "Did nothing, because it was not required"
lab var nbc_cope9 "Reduced savings"
lab var nbc_cope10 "Taking collateral loan"
lab var nbc_cope11 "Requesting provision from parents (or) relatives"
lab var nbc_cope12 "Taking the cash advance from the work"
lab var nbc_cope13 "Relying on the donation of employers"
lab var nbc_cope14 "Donations from charities, monasteries, or other institutions"
lab var nbc_cope888 "Other (specify)"
lab var nbc_cope666 "Refused"
lab var nbc_cope_oth "Please specify other coping mechanism."
