
* purpose
* hh dataset labeling 

* PN_Village_Survey_FINAL

lab var starttime "Start time "
lab var svy_date "Survey Date"
lab var starttime_c "Start time "
lab var endtime "End time"
lab var endtime_c "End time"
lab var org_team "Organization name"
lab var svy_team "Survey Team Number. "
lab var superv_name "Supervisor Name"
lab var interv_name "Interviewer Name"
lab var enu_name "Enumerator name"
lab var cluster_cat "Cluster type"
lab var geo_town "Township Name"
lab var geo_vt "Village tract name"
lab var vt_cluster_cat "Village Tract Cluster category"
lab var geo_vill "Village name"
lab var vill_data_yes "Did you able to make data collection at this village? "
lab var vill_data_no "Why were you not able to make data collection in this village?"
lab var vill_data_no1 "Security concern"
lab var vill_data_no2 "Weather condition"
lab var vill_data_no888 "Other concern"
lab var vill_data_no_oth "Please specify the other."
lab var rpl_cluster_cat "Cluster type"
lab var rpl_geo_town "Township Name"
lab var rpl_geo_vt "Replaced Village tract name"
lab var rpl_vt_cluster_cat "Replaced Village Tract Cluster category"
lab var rpl_geo_vill "Replaced Village name"
lab var rpl_vill_data_yes "Did you able to make data collection at this village? "
lab var rpl_vill_data_no "Why were you not able to make data collection in this village?"
lab var rpl_vill_data_no1 "Security concern"
lab var rpl_vill_data_no2 "Weather condition"
lab var rpl_vill_data_no888 "Other concern"
lab var rpl_vill_data_no_oth "Please specify the other."
lab var will_participate "Do you understand these conditions and are you still willing to participate?"
lab var respd_name "Respondent's name "
lab var respd_sex "Respondent's gender "
lab var respd_role "Respondent role and position"
lab var respd_role_oth "Please specify the other."
lab var respd_role_yrs "How long have you been in that position? "
lab var respd_1stround "Did you answer the Project Nourish first-round village-level questionnaires? (Provide the estimated data collection time for first round data collection)"
lab var demo_hh_number "Number"
lab var demo_hh_source "Source of Data"
lab var demo_hh_updated "Updated by when?"
lab var demo_hh_change "Did it change significantly after February 2021? (Yes/No/Not Sure)"
lab var demo_hh_scale "If yes, was it increasing or decreasing compared to before February 2021?"
lab var demo_pop_number "Number"
lab var demo_pop_source "Source of Data"
lab var demo_pop_updated "Updated by when?"
lab var demo_pop_change "Did it change significantly after February 2021? (Yes/No/Not Sure)"
lab var demo_pop_scale "If yes, was it increasing or decreasing compared to before February 2021?"
lab var demo_u5_number "Number"
lab var demo_u5_source "Source of Data"
lab var demo_u5_updated "Updated by when?"
lab var demo_u5_change "Did it change significantly after February 2021? (Yes/No/Not Sure)"
lab var demo_u5_scale "If yes, was it increasing or decreasing compared to before February 2021?"
lab var demo_u2_number "Number"
lab var demo_u2_source "Source of Data"
lab var demo_u2_updated "Updated by when?"
lab var demo_u2_change "Did it change significantly after February 2021? (Yes/No/Not Sure)"
lab var demo_u2_scale "If yes, was it increasing or decreasing compared to before February 2021?"
lab var demo_plw_number "Number"
lab var demo_plw_source "Source of Data"
lab var demo_plw_updated "Updated by when?"
lab var demo_plw_change "Did it change significantly after February 2021?"
lab var demo_plw_scale "If yes, was it increasing or decreasing compared to before February 2021?"
lab var demo_migrate "Are any households with their members migrated to other areas in your village? "
lab var demo_migrate_note "If yes, please map the migration information based on the following questions."
lab var demo_migrate_num "Please put the number of reasons you are going to report. "
lab var demo_idp "Do your villages host any displaced people after early 2021? "
lab var demo_idp_note "If yes, please map the displacement information based on the following questions."
lab var demo_idp_num "Please put the number of reasons you are going to report. "
lab var demo_dspl "Did people from your village displace to other areas after early 2021? "
lab var demo_dspl_note "If yes, please map the displacement information based on the following questions."
lab var demo_dspl_num "Please put the number of reasons you are going to report. "
lab var hfc_vill "What is the type of health facilities present in your village? "
lab var hfc_vill1 "Government – SRHC"
lab var hfc_vill2 "Government – RHC"
lab var hfc_vill3 "Government - Station Hospital"
lab var hfc_vill4 "EHO – Clinic or Village Tract Health Center"
lab var hfc_vill5 "EHO teaching hospital"
lab var hfc_vill6 "EHO - Mobile team"
lab var hfc_vill888 "Other (specify)"
lab var hfc_vill0 "None of them"
lab var hfc_vill_oth "Please specify the other."
lab var hfc_vill_staff "Does the health staff always present in that health facility (the most frequently use one)?"
lab var hf_vill_season "If not, in which season(s) does the health staff absent from that facility?"
lab var hf_vill_season1 "Summer"
lab var hf_vill_season2 "Raining"
lab var hf_vill_season3 "Winter"
lab var hf_vill_season0 "Not a seasonal"
lab var hfc_near "If not, what is the nearest health facility to your village?"
lab var hfc_near1 "Government – SRHC"
lab var hfc_near2 "Government – RHC"
lab var hfc_near3 "Government - Station Hospital"
lab var hfc_near4 "EHO – Clinic or Village Tract Health Center"
lab var hfc_near5 "EHO teaching hospital"
lab var hfc_near6 "EHO - Mobile team"
lab var hfc_near888 "Other (specify)"
lab var hfc_near0 "None of them"
lab var hfc_near_dist_note "Travel distance by motorcycle to that nearest health facilities"
lab var hfc_near_dist_dry "hours for round trip (in dry season)"
lab var hfc_near_dist_rain "hours for round trip (in raining season)"
lab var hfc_near_staff "Does the health staff always present in that health facility(ies)?"
lab var hfc_near_season "If not, in which season(s) does the health staff absent from that facility?"
lab var hfc_near_season1 "Summer"
lab var hfc_near_season2 "Raining"
lab var hfc_near_season3 "Winter"
lab var hfc_near_season0 "Not a seasonal"
lab var hfc_visit "Health care visit to your village"
lab var hfc_visit1 "EHO"
lab var hfc_visit2 "Government"
lab var hfc_visit888 "Other (Specify)"
lab var hfc_visit_oth "Please specify the other."
lab var hfc_visit_eho_type "Type of Visit"
lab var hfc_visit_eho_type1 "ANC"
lab var hfc_visit_eho_type2 "Immunization"
lab var hfc_visit_eho_type3 "Nutrition Promotion"
lab var hfc_visit_eho_type888 "Other (specify)"
lab var hfc_visit_eho_type_oth "Please specify the other."
lab var hfc_visit_eho_freq "Frequency of Visit – in average quarter "
lab var hfc_visit_eho_past "Did it change significantly compared to last year? "
lab var hfc_visit_eho_coup "Did it change significantly compared to before early 2021?"
lab var hfc_visit_gov_type "Type of Visit"
lab var hfc_visit_gov_type1 "ANC"
lab var hfc_visit_gov_type2 "Immunization"
lab var hfc_visit_gov_type3 "Nutrition Promotion"
lab var hfc_visit_gov_type888 "Other (specify)"
lab var hfc_visit_gov_type_oth "Please specify the other."
lab var hfc_visit_gov_freq "Frequency of Visit – in average quarter (per type)"
lab var hfc_visit_gov_past "Did it change significantly compared to last year? "
lab var hfc_visit_gov_coup "Did it change significantly compared to before early 2021?"
lab var hfc_visit_othpty_type "Type of Visit"
lab var hfc_visit_othpty_type1 "ANC"
lab var hfc_visit_othpty_type2 "Immunization"
lab var hfc_visit_othpty_type3 "Nutrition Promotion"
lab var hfc_visit_othpty_type888 "Other (specify)"
lab var hfc_visit_othpty_type_oth "Please specify the other."
lab var hfc_visit_othpty_freq "Frequency of Visit – in average quarter (per type)"
lab var hfc_visit_othpty_past "Did it change significantly compared to last year? "
lab var hfc_visit_othpty_coup "Did it change significantly compared to before early 2021?"
lab var hfc_diseases "What are the main health concerns in your village? (at most 5 type of diseases)"
lab var hfc_diseases1 " Diarrhea"
lab var hfc_diseases2 " Eye infections"
lab var hfc_diseases3 " Vomiting"
lab var hfc_diseases4 " Dehydration"
lab var hfc_diseases5 " Snake bites"
lab var hfc_diseases6 " Fever"
lab var hfc_diseases7 " Cough and fever (ARI)"
lab var hfc_diseases8 " Skin disease"
lab var hfc_diseases9 " Injuries/trauma"
lab var hfc_diseases10 " Death of mother and/or children following delivery"
lab var hfc_diseases11 " Chronic diseases (e.g, hypertension, diabetes)"
lab var hfc_diseases12 " Psychosocial illness"
lab var hfc_diseases888 " Other (specify) "
lab var hfc_diseases999 " Don't know/ Don't remember"
lab var hfc_diseases777 " Refused"
lab var hfc_diseases_oth "Please specify the other."
lab var hfc_diarrhea_past "If yes, did it change significantly compared to last year? "
lab var hfc_diarrhea_coup "If yes, did it change significantly compared to before early 2021?"
lab var hfc_eye_past "If yes, did it change significantly compared to last year? "
lab var hfc_eye_coup "If yes, did it change significantly compared to before early 2021?"
lab var hfc_vomit_past "If yes, did it change significantly compared to last year? "
lab var hfc_vomit_coup "If yes, did it change significantly compared to before early 2021?"
lab var hfc_dehydra_past "If yes, did it change significantly compared to last year? "
lab var hfc_dehydra_coup "If yes, did it change significantly compared to before early 2021?"
lab var hfc_snake_past "If yes, did it change significantly compared to last year? "
lab var hfc_snake_coup "If yes, did it change significantly compared to before early 2021?"
lab var hfc_fever_past "If yes, did it change significantly compared to last year? "
lab var hfc_fever_coup "If yes, did it change significantly compared to before early 2021?"
lab var hfc_ari_past "If yes, did it change significantly compared to last year? "
lab var hfc_ari_coup "If yes, did it change significantly compared to before early 2021?"
lab var hfc_skind_past "If yes, did it change significantly compared to last year? "
lab var hfc_skind_coup "If yes, did it change significantly compared to before early 2021?"
lab var hfc_trauma_past "If yes, did it change significantly compared to last year? "
lab var hfc_trauma_coup "If yes, did it change significantly compared to before early 2021?"
lab var hfc_mmortal_past "If yes, did it change significantly compared to last year? "
lab var hfc_mmortal_coup "If yes, did it change significantly compared to before early 2021?"
lab var hfc_chronic_past "If yes, did it change significantly compared to last year? "
lab var hfc_chronic_coup "If yes, did it change significantly compared to before early 2021?"
lab var hfc_psycho_past "If yes, did it change significantly compared to last year? "
lab var hfc_psycho_coup "If yes, did it change significantly compared to before early 2021?"
lab var hfc_othdises_past "If yes, did it change significantly compared to last year? "
lab var hfc_othdises_coup "If yes, did it change significantly compared to before early 2021?"
lab var hfc_mnut_note "Malnutrition Cases"
lab var hfc_mnut_p_num "Number of U5 Children"
lab var hfc_mnut_p_past "Did it change significantly compared to last year?"
lab var hfc_mnut_p_coup "Did it change significantly compared to before early 2021?"
lab var hfc_mnut_c_num "Number of U5 Children"
lab var hfc_mnut_c_past "Did it change significantly compared to last year?"
lab var hfc_mnut_c_coup "Did it change significantly compared to before early 2021?"
lab var hfc_mnut_t_num "Number of U5 Children"
lab var hfc_mnut_t_past "Did it change significantly compared to last year?"
lab var hfc_mnut_t_coup "Did it change significantly compared to before early 2021?"
lab var hfc_covid_note "Covid-19 information "
lab var hfc_covid_s_case "Number cases"
lab var hfc_covid_s_past "Did it change significantly compared to last year?"
lab var hfc_covid_s_coup "Did it change significantly compared to before early 2021?"
lab var hfc_covid_c_case "Number cases"
lab var hfc_covid_c_past "Did it change significantly compared to last year?"
lab var hfc_covid_c_coup "Did it change significantly compared to before early 2021?"
lab var hfc_covid_prev_case "Have Covid-19 prevention activities?"
lab var hfc_covid_prev_past "Did it change significantly compared to last year?"
lab var hfc_covid_prev_coup "Did it change significantly compared to before early 2021?"
lab var mkt_hshop_vill "Is there any home-shop present in the village? "
lab var mkt_vill "Is there any market present in the village? "
lab var mkt_vill_type "3.	Type of market?"
lab var mkt_vill_days "If yes, does it operate every day or only the number of days per week?"
lab var mkt_near_note "If not, where is the nearest market to your village? (Travel distance by motorcycle) "
lab var mkt_near_dist_dry "hours for round trip (in dry season)"
lab var mkt_near_dist_rain "hours for round trip (in raining season)"
lab var mkt_near_type "Type of market? "
lab var mkt_near_days "Does that nearest market operate every day or only the number of days per week?"
lab var mkt_mobile_car "Does the mobile market (selling stuff by car/light truck) come to your village at least once a month? "
lab var mkt_mobile_mbike "Does the mobile market (selling stuff by motorbike) come to your village at least once a month? "
lab var mkt_comod_note "What are the prices of the main commodities? [cheapest category in each commodity]"
lab var mkt_comod_rice "rice"
lab var mkt_comod_bean "bean"
lab var mkt_comod_salt "salt"
lab var mkt_comod_oil "oil "
lab var mkt_comod_chicken "meat – chicken"
lab var mkt_comod_pork "meat – pork "
lab var mkt_comod_beef "meat – beef"
lab var lh_note "What are the significant livelihoods of your village? (at most 5 categories)"
lab var lh_num "Please put the number of livelihood categories you are going to report"
lab var lh_cope_note "Common coping strategies – (self-reported)"
lab var lh_cope "Have households practiced the following coping strategies in the last 6 months?"
lab var lh_cope1 "Reduce food intake"
lab var lh_cope2 "Eating wild food/less preferred foods/low quality food"
lab var lh_cope3 "Increase in borrowing for consumption purposes"
lab var lh_cope4 "Sale of household assets (cooking utensils, jewelry, etc.)"
lab var lh_cope5 "Sale of productive assets (tools, animals, machinery, land)"
lab var lh_cope6 "Migration to other locations"
lab var lh_cope7 "Reliance on external support (e.g., food/cash assistance)"
lab var lh_cope8 "Use of grain bank/emergency community fund"
lab var lh_cope0 "No coping strategy available"
lab var lh_cope888 "Other (Please specify)"
lab var lh_cope999 "Don't know/ Don't remember"
lab var lh_cope777 "Refused"
lab var lh_cope_oth "Please specify the other."
lab var lh_redfood_hh "Proportion of HH "
lab var lh_redfood_past "Did it change significantly compared to last year?"
lab var lh_redfood_coup "Did it change significantly compared to before early 2021?"
lab var lh_lqfood_hh "Proportion of HH "
lab var lh_lqfood_past "Did it change significantly compared to last year?"
lab var lh_lqfood_coup "Did it change significantly compared to before early 2021?"
lab var lh_bfood_hh "Proportion of HH "
lab var lh_bfood_past "Did it change significantly compared to last year?"
lab var lh_bfood_coup "Did it change significantly compared to before early 2021?"
lab var lh_assets_hh "Proportion of HH "
lab var lh_assets_past "Did it change significantly compared to last year?"
lab var lh_assets_coup "Did it change significantly compared to before early 2021?"
lab var lh_passets_hh "Proportion of HH "
lab var lh_passets_past "Did it change significantly compared to last year?"
lab var lh_passets_coup "Did it change significantly compared to before early 2021?"
lab var lh_migt_hh "Proportion of HH "
lab var lh_migt_past "Did it change significantly compared to last year?"
lab var lh_migt_coup "Did it change significantly compared to before early 2021?"
lab var lh_extsup_hh "Proportion of HH "
lab var lh_extsup_past "Did it change significantly compared to last year?"
lab var lh_extsup_coup "Did it change significantly compared to before early 2021?"
lab var lh_fund_hh "Proportion of HH "
lab var lh_fund_past "Did it change significantly compared to last year?"
lab var lh_fund_coup "Did it change significantly compared to before early 2021?"
lab var lh_othm_hh "Proportion of HH "
lab var lh_othm_past "Did it change significantly compared to last year?"
lab var lh_othm_coup "Did it change significantly compared to before early 2021?"
lab var pn_note "Project implemented or has been implementing since 2020 (recall period 3 years)"
lab var proj_num "Please put the number of projects you are going to report"
lab var pn_imple_note "Project Nourished Implementation "
lab var pn_sbcc_yn "Do you know this project activity? - Nutrition SBCC activities"
lab var pn_sbcc_start "Staring date (year)"
lab var pn_sbcc_freq "Number of field visit by project staff in last 6 months"
lab var pn_sbcc_past "Did it change significantly compared to last year?"
lab var pn_sbcc_past_why "What are the reasons of those changes (if answered increase or decrease in first question)"
lab var pn_muac_yn "Do you know this project activity? - MUAC screening"
lab var pn_muac_start "Staring date (year)"
lab var pn_muac_freq "Number of field visit by project staff in last 6 months"
lab var pn_muac_past "Did it change significantly compared to last year?"
lab var pn_muac_past_why "What are the reasons of those changes (if answered increase or decrease in first question)"
lab var pn_wsbcc_yn "Do you know this project activity? - WASH SBCC activities"
lab var pn_wsbcc_start "Staring date (year)"
lab var pn_wsbcc_freq "Number of field visit by project staff in last 6 months"
lab var pn_wsbcc_past "Did it change significantly compared to last year?"
lab var pn_wsbcc_past_why "What are the reasons of those changes (if answered increase or decrease in first question)"
lab var pn_wash_yn "Do you know this project activity? - WASH infrastructure support"
lab var pn_wash_start "Staring date (year)"
lab var pn_wash_freq "Number of field visit by project staff in last 6 months"
lab var pn_wash_past "Did it change significantly compared to last year?"
lab var pn_wash_past_why "What are the reasons of those changes (if answered increase or decrease in first question)"
lab var pn_emgy_yn "Do you know this project activity? - Emergency response activities (Cash for food support, food basket distribution, hygiene kit distribution)"
lab var pn_emgy_start "Staring date (year)"
lab var pn_emgy_freq "Number of field visit by project staff in last 6 months"
lab var pn_emgy_past "Did it change significantly compared to last year?"
lab var pn_emgy_past_why "What are the reasons of those changes (if answered increase or decrease in first question)"
lab var pn_hgdn_yn "Do you know this project activity? - Home Gardening activities"
lab var pn_hgdn_start "Staring date (year)"
lab var pn_hgdn_freq "Number of field visit by project staff in last 6 months"
lab var pn_hgdn_past "Did it change significantly compared to last year?"
lab var pn_hgdn_past_why "What are the reasons of those changes (if answered increase or decrease in first question)"
lab var pn_msg_yn "Do you know this project activity? - Mother Support Group"
lab var pn_msg_start "Staring date (year)"
lab var pn_msg_freq "Number of field visit by project staff in last 6 months"
lab var pn_msg_past "Did it change significantly compared to last year?"
lab var pn_msg_past_why "What are the reasons of those changes (if answered increase or decrease in first question)"
lab var submission_time "Submission time"
lab var submission_time_c "Submission time"
lab var submitted_by "Submission account"
lab var org_name "Organization name"
lab var township_name "Township name"
lab var geo_eho_vt_name "EHO Village Tract name"
lab var geo_eho_vill_name "EHO Village name"
lab var stratum "Stratum number"
lab var num_cluster "Cluster number"
lab var vill_samplesize "Village sample size"
lab var sample_check "Sample Check (have enough U5 HH or not)"
lab var township_name_n "Township Name"
lab var geo_eho_vt_name_n "EHO Village Tract name"
lab var cluster_cat_str "Cluster category"
lab var geo_eho_vill_name_n "EHO Village name"
lab var stratum_n "Stratum number"
lab var num_cluster_n "Cluster number"
lab var vill_samplesize_n "Village sample size"
lab var sample_check_n "Sample Check (have enough U5 HH or not)"
